on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: "8.1"
    secrets:
      infection_badge_api_key:
        required: true
      stryker_dashboard_api_key:
        required: true

jobs:
  mutation:
    name: "Composer Script - Mutation Tests"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: pcov
          tools: composer:v2
          php-version: "${{ inputs.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ matrix.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ inputs.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Mutation Tests"
        run: "composer test:mutation"
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.infection_badge_api_key }}
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.stryker_dashboard_api_key }}