on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: "8.1"

jobs:
  static-analyze:
    name: "Composer Script - Static Analyze"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: pcov
          tools: composer:v2
          php-version: "${{ inputs.php-version }}"
          ini-values: memory_limit=-1

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
          key: "php-${{ inputs.php-version }}-locked-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ inputs.php-version }}-locked-composer-

      - name: "Install locked dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Static Analyze"
        run: "composer static:analyze"